### ISSUE TITLE
64bit Reflective DLL Injection

### ISSUE THREAD

**Issue by ghost** [fdiskyou/injectAllTheThings#2]
Causes the target to crash. The loader itself runs fine, as soon as the remote thread is started it crashes.

**Comment by NewHJX** [comment]
@ghost maybe it is caused by  Fault Tolerant Heap

**Comment by fdiskyou** [comment]
Yes, and by the way which technique are you using, what's the remote process, and which DLL are you using?

**Comment by NewHJX** [comment]
NtCreateThreadEx+taskmgr.exe     win7 x64 
but some trouble when I wrote it as a service process.  
Any Suggestions?

**Comment by fdiskyou** [comment]
I don't know what you mean by "wrote it as a service process". Do you mind to elaborate?
