### ISSUE TITLE
Build Error  in VB2017 running on windows10 64bit

### ISSUE THREAD

**Issue by MominSohail** [fdiskyou/injectAllTheThings#3]
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "copy ..\Release\dllmain.dll ..\bin\dllmain_32.dll
:VCEnd" exited with code 1.	dllmain	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	133	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "copy ..\Release\dllpoc.dll ..\bin\dllpoc_32.dll
:VCEnd" exited with code 1.	dllpoc	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	133	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "copy ..\Release\rdll.dll ..\bin\rdll_32.dll
:VCEnd" exited with code 1.	rdll	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	133	

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3073	The command "copy ..\Release\injectAllTheThings.exe ..\bin\injectAllTheThings_32.exe
:VCEnd" exited with code 1.	injectAllTheThings	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets	133

**Comment by fdiskyou** [comment]
The build is ok, in the project properties I'm copying the PE files to a bin directory. I guess you either deleted it manually or for some reason it is missing. Create the dir (or adjust the project properties) and the errors will disappear.
