### ISSUE TITLE
DLL injection via NtCreateThreadEx() not working on Windows 10 64-bit (1709/1803)

### ISSUE THREAD

**Issue by WildByDesign** [fdiskyou/injectAllTheThings#4]
All injections are working for me very well except for NtCreateThreadEx().  It is failing for both 32-bit and 64-bit processes on Windows 10 64-bit system build 1709 and 1803 as well.

Error: 
`[-] NtCreateThread() is only available in Windows Vista and up.`

I have tried numerous 32-bit processes and 64-bit processes on both platforms (1709 and 1803 64-bit) and have always received this same error.

However, the GUI program RemoteDLL https://securityxploded.com/remotedll.php has this same NtCreateThreadEx() injection option and, for whatever reason, the same injection method is successful with that program on the same 32-bit and 64-bit processes on the same platforms in which InjectAllTheThings injection for NtCreateThreadEx() has been failing.

Do you know if there is a way to resolve this issue?

Thank you for your time.

**Comment by fdiskyou** [comment]
I didn't test it in Windows 10, looking at the error it seems my logic to detect the Windows version is not working for Windows 10. Just search for that string in the code. Remove that check (assuming you are in Windows 10) and it should work.

**Comment by WildByDesign** [comment]
Thank you.  Yes, after removing the OS version check the NtCreateThreadEx() DLL injection is working now on Windows 10 RS4 1803.

32-bit injection is successful but 64-bit injection fails likely due to Windows 10 process mitigations that are enforced stronger by default on all 64-bit apps.

**Comment by fdiskyou** [comment]
Thank you for validating that. I will fix the OS check when I get time.

**Comment by attilakrupl** [comment]
Hi,

did you manage to find a way around this issue on x64 platform? The implementation works for x86 platform without an issue, but when I'm trying to compile for x64 I'm receiving the following error: STATUS_ACCESS_VIOLATION (-1073741819). And that's the best case scenario, because if I keep trying to change the argument types for the buffer, I'm getting the STATUS_INVALID_PARAMETER (-1073741811) error. 

Should we just accept that there's no way around this? 

Thanks!

**Comment by KooroshRZ** [comment]
Hi,

The NtCreateThreadEx method works fine for 32 bit processes but does not work for 64 bit windows without throwing an error.
all goes fine and NtCreateThread starts successfully without any error but the payload does not run inside it ;//
I read somewhere that the ntbuffer fields values are different for 32 bit and 64 bit processes but I don't know the exact difference

**Comment by fdiskyou** [comment]
Just tested it on Windows 10 1903 x64. Works for me with notepad.

**Comment by KooroshRZ** [comment]
Actually I found a fix for this problem from a forum site
there is no need for that weird unknown buffer structure
just remove it and replace it with nullptr
it works fine for both Win32 and x64 processes even in windows 10

**Comment by fdiskyou** [comment]
I'll have a look. Thank you.
