### ISSUE TITLE
NtCreateThreadEx() on Windows 10 64-bit 1803 - Out of Virtual Memory

### ISSUE THREAD

**Issue by WildByDesign** [fdiskyou/injectAllTheThings#5]
After removing the OS version check as suggested from https://github.com/fdiskyou/injectAllTheThings/issues/4 , the DLL injection via NtCreateThreadEx() is working correctly now.  32-bit injection is successful.  However, 64-bit injection fails consistently and I was able to capture some more details to share. Initially I was thinking that it had something to do with triggering a process mitigation on the 64-bit binary.  But I was unable to find specific detail on process mitigation trigger. But it does consistently cause an Event ID to appear upon each failure.

_Log Name:      System
Source:        Application Popup
Date:          5/12/2018 9:45:21 AM
**Event ID:      26**
Task Category: None
Level:         Information
Keywords:      
User:          SYSTEM
Computer:      WIN10-ULTRABOOK
Description:
Application popup: 
**Windows - Out of Virtual Memory : Your system is low on virtual memory. To ensure that Windows runs properly, increase the size of your virtual memory paging file. For more information, see Help.**_ 

The error code from InjectAllTheThings is:
**[-] NtCreateThreadEx Failed! [0][c000012d]**

My 64-bit system (Windows 10 RS4 / 1803) has 16GB RAM.  As a part of troubleshooting this specific issue, I tried increasing the paging file size to 4096MB but still the issue persists.

Anyway, I hope these details may be beneficial in finding the cause of this bug.  Thank you for this great injection tool.  This is by far one of the most thorough injection tools at this current time. Keep up the great work!

**Comment by fdiskyou** [comment]
Can't reproduce. Works well for me on Win 10 1903 X64.
